### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by buchold** [kanhua/pyCONTIN#1]
Hey the idea of pyCONTIN is genius.
All dynamic light scattering software lacks some features and being able to use CONTIN in python would solve a lot of issus.
I just wanted to ask, what the status is, and if you still continue developing. As far as I could I would help you!
Greets 
Philipp

**Comment by kanhua** [comment]
Thank you for your interest. Sorry I haven't updated this repository for some time. I will upload a working version of this software soon.

**Comment by buchold** [comment]
Perfect! Do you alraedy have a working version?

**Comment by kanhua** [comment]
I am sorry for the delay because of my personal holidays and other commitments. I wrote a simple example file for testing and added more information in the README file. You can give it a try and let me know if you any problems or questions.

**Comment by buchold** [comment]
Now I was on a conference.
Thanks for the work. I will test it during the week
Philipp

_______________Philipp Buchold_
2 Rue de l'Ancien Champ de Mars
38000 Grenoble, FR
+33 782 29 40 36

2015-08-27 4:08 GMT+02:00 kanhua notifications@github.com:
